### ISSUE TITLE
Building with varnish 4.0.3

### ISSUE THREAD

**Issue by alistar79** [varnish/libvmod-digest#13]
Evening,

Struggling to get this to build with Varnish 4.0.  The 3.0 and 4.0 branch complains my varnish source is invalid like they are both only 3.0 compatible?

The master branch gets further and when it makes it yields this error:

make  all-recursive
make[1]: Entering directory `trunk/libvmod-digest'
Making all in src
make[2]: Entering directory `trunk/libvmod-digest/src'
/bin/sh ../libtool --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -Wall -Wextra   -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c -o vmod_digest.lo vmod_digest.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c vmod_digest.c  -fPIC -DPIC -o .libs/vmod_digest.o
vmod_digest.c:91: warning: ‘enum vcl_event_e’ declared inside parameter list
vmod_digest.c:91: error: parameter 3 (‘e’) has incomplete type
vmod_digest.c: In function ‘init_function’:
vmod_digest.c:96: error: ‘VCL_EVENT_LOAD’ undeclared (first use in this function)
vmod_digest.c:96: error: (Each undeclared identifier is reported only once
vmod_digest.c:96: error: for each function it appears in.)
vmod_digest.c:91: warning: unused parameter ‘e’
vmod_digest.c: In function ‘vmod_hmac_generic’:
vmod_digest.c:284: warning: comparison between signed and unsigned integer expressions
vmod_digest.c:287: warning: comparison between signed and unsigned integer expressions
vmod_digest.c: In function ‘vmod_hash_generic’:
vmod_digest.c:355: warning: comparison between signed and unsigned integer expressions
make[2]: *** [vmod_digest.lo] Error 1
make[2]: Leaving directory `trunk/libvmod-digest/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `trunk/libvmod-digest'
make: *** [all] Error 2

Is master 4.1 only?

**Comment by fgsch** [comment]
master is 4.1 only. 

4.0 should build using the 4.0 branch. If not please post the error.

**Comment by Francois-v3** [comment]
Hi,

i had the same problem recently, there's no 4.0 branch.

I've fixed the problem by using 4.1 branch and rollbacking just before 
the "4.0 to 4.1" migration.

Happy new year

Le 04/01/2016 17:58, Federico G. Schwindt a écrit :
>
> master is 4.1 only.
>
> 4.0 should build using the 4.0 branch. If not please post the error.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/varnish/libvmod-digest/issues/13#issuecomment-168733767>.
>

-- 
François Veux - +33633267508

**Comment by fgsch** [comment]
I can see the 4.0 branch just fine. Are you sure?
There is no 4.1 branch though, since 4.1 is tracked in master.

**Comment by Francois-v3** [comment]
It's back today, but was absent several weeks ago ... and master did not 
compile with 4.0 due to an migration to 4.1.

There's a "Reestablish support for 4.0"  21 days ago ... this should be 
the issue.


Le 04/01/2016 19:48, Federico G. Schwindt a écrit :
>
> I can see the 4.0 branch just fine. Are you sure?
> There is no 4.1 branch though, since 4.1 is tracked in master.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/varnish/libvmod-digest/issues/13#issuecomment-168765329>.
>

-- 
François Veux - +33633267508

**Comment by alistar79** [comment]
Sorry false alarm seems there is no error.  I had an issue in my build automation that left me with a mix of both branches! All fixed now :)  Many thanks!!

Alister

**Comment by razvanphp** [comment]
I have the same problem, but I'm pretty sure I'm on the right branch. Any idea?

```
vagrant@aboutyou:~/libvmod-digest$ sudo varnishd -V
varnishd (varnish-4.0.3 revision b8c4a34)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2014 Varnish Software AS
vagrant@aboutyou:~/libvmod-digest$ make
make  all-recursive
make[1]: Entering directory '/home/vagrant/libvmod-digest'
Making all in src
make[2]: Entering directory '/home/vagrant/libvmod-digest/src'
/usr/share/varnish/vmodtool.py ../src/vmod_digest.vcc
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -Wall -Wextra   -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c -o vmod_digest.lo vmod_digest.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c vmod_digest.c  -fPIC -DPIC -o .libs/vmod_digest.o
vmod_digest.c: In function 'vmod_hmac_generic':
vmod_digest.c:280:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (j = 0; j < blocksize; j++) {
                ^
In file included from /usr/include/varnish/common/common.h:37:0,
                 from /usr/include/varnish/cache/cache.h:37,
                 from vmod_digest.c:55:
vmod_digest.c:283:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   assert((hexptr-hexenc)<(2*blocksize + 3));
                         ^
/usr/include/varnish/vas.h:59:8: note: in definition of macro 'assert'
  if (!(e)) {       \
        ^
vmod_digest.c: In function 'vmod_hash_generic':
vmod_digest.c:351:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i<mhash_get_block_size(hash);i++) {
               ^
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vmod_digest.lo -MD -MP -MF .deps/vmod_digest.Tpo -c vmod_digest.c -o vmod_digest.o >/dev/null 2>&1
mv -f .deps/vmod_digest.Tpo .deps/vmod_digest.Plo
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -Wall -Wextra   -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c -o vcc_if.lo vcc_if.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c vcc_if.c  -fPIC -DPIC -o .libs/vcc_if.o
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Wextra -g -O2 -MT vcc_if.lo -MD -MP -MF .deps/vcc_if.Tpo -c vcc_if.c -o vcc_if.o >/dev/null 2>&1
mv -f .deps/vcc_if.Tpo .deps/vcc_if.Plo
/bin/bash ../libtool  --tag=CC   --mode=link gcc -std=gnu99  -g -O2 -module -export-dynamic -avoid-version -shared -lmhash  -o libvmod_digest.la -rpath /usr/lib/varnish/vmods vmod_digest.lo vcc_if.lo
libtool: link: gcc -std=gnu99 -shared  -fPIC -DPIC  .libs/vmod_digest.o .libs/vcc_if.o   -lmhash  -O2   -Wl,-soname -Wl,libvmod_digest.so -o .libs/libvmod_digest.so
libtool: link: ( cd ".libs" && rm -f "libvmod_digest.la" && ln -s "../libvmod_digest.la" "libvmod_digest.la" )
make[2]: Leaving directory '/home/vagrant/libvmod-digest/src'
make[2]: Entering directory '/home/vagrant/libvmod-digest'
rst2man README.rst vmod_digest.3
make[2]: Leaving directory '/home/vagrant/libvmod-digest'
make[1]: Leaving directory '/home/vagrant/libvmod-digest'
vagrant@aboutyou:~/libvmod-digest$ git status
On branch 4.0
Your branch is up-to-date with 'origin/4.0'.
nothing to commit, working directory clean
vagrant@aboutyou:~/libvmod-digest$
```

**Comment by rezan** [comment]
@razvanphp This compiled fine. There are a few warnings which exist in master at the moment. I made an issue #16.

**Comment by razvanphp** [comment]
Yes, you are right, sorry, but still, the warnings are also in 4.0 branch, so you might wanna fix those too. Thank you!
