### ISSUE TITLE
VCL compilation fails with current varnish (6.2.0)

### ISSUE THREAD

**Issue by cst152** [varnish/libvmod-digest#29]
Hi,

I'm currently having issues starting varnish with the digest module. `import digest;` causes the following error during VCL compilation:

```
Error:
Message from VCC-compiler:
Could not load VMOD digest
	File name: /usr/lib/varnish/vmods/libvmod_digest.so
	dlerror: /usr/lib/varnish/vmods/libvmod_digest.so: undefined symbol: vmod_init_function
('/etc/varnish/default.vcl' Line 16 Pos 8)
import digest;
-------######-

Running VCC-compiler failed, exited with 2
VCL compilation failed
```

I'm using a self-compiled varnish at version 6.2.0 and the master branch of libvmod-digest on Debian. I noticed this issue about a month ago with Varnish 6.1.1, though.

**Comment by Dridi** [comment]
Yes, 6.2 introduced some "havoc" and normally it should be easy to solve:

https://varnish-cache.org/lists/pipermail/varnish-dev/2019-February/009327.html

Would you like to attempt a pull request?

**Comment by Dridi** [comment]
Here is an example of such a migration: https://github.com/Dridi/libvmod-querystring/commit/b657fb4c08197e5c6a62d6be1a4bdbbd27796029

**Comment by cst152** [comment]
I'll gladly help, though I'm not particularly an expert on the internals of Varnish. Or vmods. Or c for that matter :)

I made some changes to vmod_digest.c as you can review [here](https://github.com/cst152/libvmod-digest/commit/d0dac7f93046e6ef275c5c5a1b7d6aca563bd395#diff-21ec22e0d0596047bf62290ba9d35ed3). The vmod compiles as it should but I still got the same error when I launch varnish.

**Comment by Dridi** [comment]
Does it work with Varnish 6.0 too?

**Comment by cst152** [comment]
That'll take me some time to figure out. I'll get back to you.

**Comment by cst152** [comment]
Alright, it works for varnish 6.0 and 6.1. After I changed init_function into VPFX(init_function), it also seems to work with 6.2.0. I'll test it some more and issue a pull request then.

**Comment by cst152** [comment]
Pull request is issued.
